services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Frontend/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend